version: '1.0'
services:
  # webapp config
  web:
    container_name: erp_app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      express_network:
  # postgres config
  db:
    container_name: pg_database
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=erp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      express_network:
  # dbadmin config
  dashboard:
    container_name: pg_admin
    restart: always
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=mugiwarassae02@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=zuihqqwvgyhdztzc
    ports:
      - 8080:80
    networks:
      express_network:

volumes:
  pgdata:
  pgadmin:

networks:
  express_network:
