interface IReport {
	readonly company?: string
	readonly salesOrder?: string
	readonly poNumber?: string
	readonly soDate?: Date
	readonly invoice?: string
	readonly externalInvoice?: string
	readonly invoiceDate?: Date
	readonly dueDate?: Date
	readonly invoiceAccount?: string
	readonly name?: string
	readonly addressGroup?: string
	readonly packSlipDate?: Date
	readonly packingSlip?: string
	readonly externalPackingSlip?: string
	readonly salesItemNumber?: string
	readonly itemName?: string
	readonly originItemName?: string
	readonly group?: string
	readonly productDimensi?: string
	readonly thickness?: number
	readonly length?: number
	readonly lengthM?: number
	readonly colorType?: string
	readonly sizeWidth?: string
	readonly qty?: number
	readonly unit?: string
	readonly qtyInKG_PPIC?: number
	readonly qtyInKG_MKT?: number
	readonly price?: number
	readonly discPercent?: number
	readonly discValue?: number
	readonly lineDiscount?: number
	readonly headerDisc?: number
	readonly total?: number
	readonly taxCode?: string
	readonly taxTotal?: number
	readonly includeTax?: boolean
	readonly divisi?: string
	readonly kota?: string
	readonly propinsi?: string
	readonly salesDistrictId?: string
	readonly district?: string
	readonly termPay?: string
	readonly status?: string
	readonly closedDate?: Date
	readonly note1?: string
	readonly note2?: string
	readonly note3?: string
	readonly clGroup?: string
	readonly creditLimit?: number
	readonly invoicingName?: string
	readonly customGroup?: string
	readonly cityGroup?: string
	readonly countyGroup?: string
	readonly stateGroup?: string
	readonly pkp?: string
	readonly npwp?: string
	readonly nama?: string
	readonly alamat?: string
}

export class ReportDTO implements IReport {
	readonly company?: string
	readonly salesOrder?: string
	readonly poNumber?: string
	readonly soDate?: Date
	readonly invoice?: string
	readonly externalInvoice?: string
	readonly invoiceDate?: Date
	readonly dueDate?: Date
	readonly invoiceAccount?: string
	readonly name?: string
	readonly addressGroup?: string
	readonly packSlipDate?: Date
	readonly packingSlip?: string
	readonly externalPackingSlip?: string
	readonly salesItemNumber?: string
	readonly itemName?: string
	readonly originItemName?: string
	readonly group?: string
	readonly productDimensi?: string
	readonly thickness?: number
	readonly length?: number
	readonly lengthM?: number
	readonly colorType?: string
	readonly sizeWidth?: string
	readonly qty?: number
	readonly unit?: string
	readonly qtyInKG_PPIC?: number
	readonly qtyInKG_MKT?: number
	readonly price?: number
	readonly discPercent?: number
	readonly discValue?: number
	readonly lineDiscount?: number
	readonly headerDisc?: number
	readonly total?: number
	readonly taxCode?: string
	readonly taxTotal?: number
	readonly includeTax?: boolean
	readonly divisi?: string
	readonly kota?: string
	readonly propinsi?: string
	readonly salesDistrictId?: string
	readonly district?: string
	readonly termPay?: string
	readonly status?: string
	readonly closedDate?: Date
	readonly note1?: string
	readonly note2?: string
	readonly note3?: string
	readonly clGroup?: string
	readonly creditLimit?: number
	readonly invoicingName?: string
	readonly customGroup?: string
	readonly cityGroup?: string
	readonly countyGroup?: string
	readonly stateGroup?: string
	readonly pkp?: string
	readonly npwp?: string
	readonly nama?: string
	readonly alamat?: string
}